"""ашч

Revision ID: 50d3d9c151e9
Revises: 2f8c06fd3787
Create Date: 2026-02-26 05:28:36.686093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d3d9c151e9'
down_revision: Union[str, Sequence[str], None] = '2f8c06fd3787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lessons_topic_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lessons_topic_id_fkey'), 'lessons', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
