"""add_courses

Revision ID: cf58eacc3081
Revises: 50d3d9c151e9
Create Date: 2026-02-26 05:36:14.470482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf58eacc3081'
down_revision: Union[str, Sequence[str], None] = '50d3d9c151e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_course_student'), 'course_enrollments', type_='unique')
    op.drop_constraint(op.f('course_enrollments_student_id_fkey'), 'course_enrollments', type_='foreignkey')
    op.drop_constraint(op.f('course_enrollments_course_id_fkey'), 'course_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'course_enrollments', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'course_enrollments', 'courses', ['course_id'], ['id'])
    op.drop_column('course_enrollments', 'id')
    op.drop_column('course_enrollments', 'completed_at')
    op.alter_column('courses', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('courses', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('courses', 'updated_at')
    op.drop_constraint(op.f('uq_lesson_student'), 'lesson_progress', type_='unique')
    op.drop_constraint(op.f('lesson_progress_student_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_progress', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'lesson_progress', 'users', ['student_id'], ['id'])
    op.add_column('lessons', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.alter_column('lessons', 'video_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('lessons_course_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'])
    op.drop_column('lessons', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_course_id_fkey'), 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lessons', 'video_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('lessons', 'topic_id')
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lesson_progress_student_id_fkey'), 'lesson_progress', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_lesson_student'), 'lesson_progress', ['lesson_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.add_column('courses', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('courses', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('courses', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('course_enrollments', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('course_enrollments', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'course_enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('course_enrollments_course_id_fkey'), 'course_enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('course_enrollments_student_id_fkey'), 'course_enrollments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_course_student'), 'course_enrollments', ['course_id', 'student_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
